[package]
name = "week-31"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = { version = "1.5.7", features = ["derive"] }
borsh-derive = "1.5.7"
solana-program = "3.0.0"
